# Generated by Django 2.2.5 on 2019-10-31 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogging', '0005_auto_20191031_1126'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CreatePost',
        ),
    ]
